name: understudy_app
description: "An app to help you learn your lines for the big audition"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_core: ^2.25.5

  user_repository:
    path: packages/user_repository
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  url_launcher: ^6.2.5
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets: 
    - assets/background/
    - assets/logos/
    - assets/icons/
  fonts:
    - family: Courier Font
      fonts:
        - asset: assets/fonts/CourierPrime-Bold.ttf
        - asset: assets/fonts/CourierPrime-BoldItalic.ttf
        - asset: assets/fonts/CourierPrime-Regular.ttf
        - asset: assets/fonts/CourierPrime-Italic.ttf

      